name: tunzaa_market_place_challenge
description: A Tiunzaa market place challenge

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.2.0
  freezed_annotation: ^2.2.0
  go_router: ^6.0.7
  google_fonts: ^4.0.3
  hooks_riverpod: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  kt_dart: ^1.0.0
  riverpod_annotation: ^1.2.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^1.2.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
